/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Design System: Tactile Cyber-Brutalism
        'surface-container-low': '#161c1f',
        'surface-container': '#1a2024',
        'surface-container-high': '#252b2e',
        'surface-container-highest': '#303639',
        'surface-container-lowest': '#090f12',
        'surface-dim': '#0e1417',
        'surface-bright': '#343a3d',
        'surface-variant': '#303639',
        'surface': '#0e1417',
        'background': '#0e1417',
        'on-surface': '#dee3e7',
        'on-surface-variant': '#bac9cc',
        'on-background': '#dee3e7',
        'primary': '#c3f5ff',
        'primary-container': '#00e5ff',
        'primary-fixed': '#9cf0ff',
        'primary-fixed-dim': '#00daf3',
        'on-primary': '#00363d',
        'on-primary-container': '#00626e',
        'on-primary-fixed': '#001f24',
        'secondary': '#dcb8ff',
        'secondary-container': '#7701d0',
        'secondary-fixed': '#efdbff',
        'secondary-fixed-dim': '#dcb8ff',
        'on-secondary': '#480081',
        'on-secondary-container': '#dcb7ff',
        'tertiary': '#abffcb',
        'tertiary-container': '#00ee98',
        'tertiary-fixed': '#52ffac',
        'tertiary-fixed-dim': '#00e290',
        'on-tertiary': '#003920',
        'on-tertiary-container': '#00673f',
        'error': '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'outline': '#849396',
        'outline-variant': '#3b494c',
        'inverse-surface': '#dee3e7',
        'inverse-on-surface': '#2b3135',
        'inverse-primary': '#006875',
        'surface-tint': '#00daf3',
      },
      fontFamily: {
        'headline': ['Space Grotesk', 'system-ui', 'sans-serif'],
        'body': ['Inter', 'system-ui', 'sans-serif'],
        'label': ['Inter', 'system-ui', 'sans-serif'],
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        'full': '9999px',
      },
      animation: {
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'bounce-slow': 'bounce 2s infinite',
        'float': 'float 6s ease-in-out infinite',
        'glow': 'glow 2s ease-in-out infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px) rotate(0deg)' },
          '50%': { transform: 'translateY(-10px) rotate(2deg)' },
        },
        glow: {
          '0%, 100%': { boxShadow: '0 0 10px rgba(0, 229, 255, 0.4)' },
          '50%': { boxShadow: '0 0 25px rgba(0, 229, 255, 0.7)' },
        },
      },
      boxShadow: {
        'extruded': '8px 8px 16px rgba(0,0,0,0.4), -4px -4px 12px rgba(255,255,255,0.03)',
        'recessed': 'inset 4px 4px 8px rgba(0,0,0,0.5), inset -2px -2px 4px rgba(255,255,255,0.05)',
        'glow-primary': '0 0 20px rgba(0, 229, 255, 0.4)',
        'glow-tertiary': '0 0 15px rgba(171, 255, 203, 0.4)',
        'glow-secondary': '0 0 15px rgba(220, 184, 255, 0.4)',
      },
    },
  },
  plugins: [],
};
